# Official node base image
FROM node:0.12

# Maintainer
MAINTAINER Ritesh Sangwan <sangwan.ritesh@yahoo.in>

# Bundle app source
COPY . /rate-my-ride-users-api

RUN apt-get update && apt-get install -y --no-install-recommends libkrb5-dev supervisor \
    && echo "//registry.npmjs.org/:_authToken=NPM_TOKEN" > ~/.npmrc \
    && cd /rate-my-ride-users-api \
    && npm install \
    && rm ~/.npmrc \
    && rm -rf /var/lib/apt/lists/*

# copy the supervisor conf file
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Exclude npm cache from the image
VOLUME /root/.npm

# expose environment variable
EXPOSE 3300

# start supervisor
CMD ["/usr/bin/supervisord"]