# Official node base image
FROM node:slim

# Maintainer
MAINTAINER Ritesh Sangwan <sangwan.ritesh@yahoo.in>

# install supervisor
RUN apt-get update && apt-get install -y supervisor

# copy the supervisor conf file
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Bundle app source
COPY . /rate-my-ride-users-api

# Exclude npm cache from the image
VOLUME /root/.npm

# Install app dependencies
RUN echo "//registry.npmjs.org/:_authToken=NPM_TOKEN" > ~/.npmrc; cd /rate-my-ride-users-api; npm install; rm ~/.npmrc

# expose environment variable
EXPOSE 3300

# start supervisor
CMD ["/usr/bin/supervisord"]